// Generic interface labels. Any key can be overridden from the `ui:` block of the site config.
const defaults = {
  browse: 'Browse',
  search: 'Search',
  search_placeholder: 'Search concepts…',
  filter_placeholder: 'Filter by label or synonym…',
  expand_all: 'Expand all',
  collapse_all: 'Collapse all',
  definition: 'Definition',
  synonyms: 'Synonyms',
  children: 'Narrower concepts',
  hierarchy_section: 'In the hierarchy',
  more: 'more',
  relations: 'Related concepts',
  implied: 'implied',
  notes: 'Notes',
  fields: 'Details',
  other_fields: 'Other fields',
  mappings: 'Mappings',
  identifiers: 'Identifiers',
  position: 'Position',
  depth: 'Depth',
  descendants: 'Concepts beneath',
  quality: 'Quality notes',
  no_flags: 'No open notes.',
  formats: 'Formats',
  contribute: 'Improve this concept',
  suggest_edit: 'Suggest an edit',
  suggest_intro: 'Change the fields below. Your suggestion is checked automatically against the vocabulary rules when you submit it, and a maintainer reviews it before it is applied.',
  field_label: 'Preferred label',
  field_parent: 'Parent concept',
  field_synonyms: 'Synonyms (one per line)',
  field_relations: 'Relations',
  add_relation: 'Add relation',
  remove: 'remove',
  new_child: 'Add a narrower concept',
  new_child_label: 'Label',
  new_child_definition: 'Definition',
  retire: 'Retire this concept',
  retire_replaced_by: 'Replaced by',
  retire_help: 'Its narrower concepts and links move to the replacement.',
  rationale: 'Why? (required)',
  your_suggestion: 'Your suggestion',
  no_changes: 'No changes yet.',
  submit_suggestion: 'Propose on GitHub',
  submit_help: 'Opens GitHub with your suggestion as a file to propose; GitHub creates the pull request for you.',
  free_form: 'Something else? Leave a free-form comment',
  edit_source: 'Edit source',
  add_notes: 'Add notes',
  edit_notes: 'Edit notes',
  open_issue: 'Open an issue',
  copy: 'Copy',
  copied: 'Copied',
  concepts: 'concepts',
  synonyms_count: 'synonyms',
  relations_count: 'cross-links',
  flagged: 'with quality notes',
  branches: 'Top-level branches',
  severity_error: 'Error',
  severity_warn: 'Warning',
  severity_info: 'Info',
  all: 'All',
  passing: 'Passing',
  check: 'Check',
  concept: 'Concept',
  branch: 'Branch',
  severity: 'Severity',
  detail: 'Detail',
  no_matches: 'No matches.',
  downloads: 'Downloads',
  per_term: 'Per-concept RDF',
  relation: 'Relation',
  predicate: 'Predicate',
  inverse: 'Shown on the target as',
  hierarchy: 'Hierarchy',
  namespace: 'Namespace',
  scheme: 'Concept scheme',
  built_from: 'Built from',
  not_found: 'Page not found',
};

export type UI = typeof defaults;
export const uiStrings = (overrides: Record<string, string> = {}): UI => ({ ...defaults, ...overrides });
