// Generic interface labels. Any key can be overridden from the `ui:` block of the site config.
const defaults = {
  browse: 'Browse',
  search: 'Search',
  search_placeholder: 'Search concepts…',
  filter_placeholder: 'Filter by label or synonym…',
  expand_all: 'Expand all',
  collapse_all: 'Collapse all',
  definition: 'Definition',
  synonyms: 'Synonyms',
  children: 'Narrower concepts',
  relations: 'Related concepts',
  implied: 'implied',
  notes: 'Notes',
  fields: 'Details',
  other_fields: 'Other fields',
  mappings: 'Mappings',
  identifiers: 'Identifiers',
  position: 'Position',
  depth: 'Depth',
  descendants: 'Concepts beneath',
  quality: 'Quality notes',
  no_flags: 'No open notes.',
  formats: 'Formats',
  contribute: 'Improve this concept',
  suggest_edit: 'Suggest an edit',
  edit_source: 'Edit source',
  add_notes: 'Add notes',
  edit_notes: 'Edit notes',
  open_issue: 'Open an issue',
  copy: 'Copy',
  copied: 'Copied',
  concepts: 'concepts',
  synonyms_count: 'synonyms',
  relations_count: 'cross-links',
  flagged: 'with quality notes',
  branches: 'Top-level branches',
  severity_error: 'Error',
  severity_warn: 'Warning',
  severity_info: 'Info',
  all: 'All',
  passing: 'Passing',
  check: 'Check',
  concept: 'Concept',
  branch: 'Branch',
  severity: 'Severity',
  detail: 'Detail',
  no_matches: 'No matches.',
  downloads: 'Downloads',
  per_term: 'Per-concept RDF',
  relation: 'Relation',
  predicate: 'Predicate',
  inverse: 'Shown on the target as',
  hierarchy: 'Hierarchy',
  namespace: 'Namespace',
  scheme: 'Concept scheme',
  built_from: 'Built from',
  not_found: 'Page not found',
};

export type UI = typeof defaults;
export const uiStrings = (overrides: Record<string, string> = {}): UI => ({ ...defaults, ...overrides });
